url: mountaye.github.io
baseurl: /blog
title: 阿掖山：一个博客
subtitle: MountAye | A Blog
author: MountAye
simple_search: http://google.com/search
description: "阿掖山：一个博客"
name: MountAye
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: Asia/Beijing
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'vendor']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ../tentative
plugins:
  - jekyll-seo-tag